# Project information
site_name: 'Kohii'
site_description: 'Android Video Playback made easy.'
site_author: '2019 Nam Nguyen, nam@ene.im'
site_url: 'https://eneim.github.io/kohii'
remote_branch: gh-pages

# Repository
repo_name: 'Kohii'
repo_url: 'https://github.com/eneim/kohii'

# Copyright
copyright: 'Copyright &copy; 2019 Nam Nguyen, nam@ene.im'

# Configuration
theme:
  name: 'material'
  language: 'en'
  favicon: 'art/favicon.ico'
  logo: 'art/ic_launcher-web.png'
  palette:
    primary: 'blue grey'
    accent: 'cyan'
  font:
    # text: 'Open Sans'
    text: 'Karla' # 'Karla', 'Noto Sans JP', 'Montserrat', 'Open Sans'
    code: 'Roboto Mono' # 'Oxygen Mono', 'Fira Code', 'Roboto Mono'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/eneim/kohii'

google_analytics:
  - 'UA-72567780-9'
  - 'auto'

# Navigation
nav:
  - 'Overview': index.md
  - 'Using Kohii':
      - 'Getting start': usage/start.md
      - 'Basic usages': usage/basic.md
      - 'Advance usages': usage/advance.md
      - 'Demo app': usage/demos.md
  - 'Extending Kohii':
      - 'Components': customize/terms.md
      - 'Custom Engine': customize/custom_engine.md
  - 'Changelog': changelog.md
  - 'API':
      - 'kohii-core': api/kohii-core/index.md
      - 'kohii-exoplayer': api/kohii-exoplayer/index.md
      - 'kohii-androidx': api/kohii-androidx/index.md
      - 'kohii-ads': api/kohii-ads/index.md
  - 'Code of Conduct': code_of_conduct.md

# CSS
extra_css:
  - 'css/main.css'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      use_pygments: True
      noclasses: True
      pygments_style: perldoc
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - footnotes


# Plugins
plugins:
  - search
  - minify:
      minify_html: true